name: Playwright
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Se inyecta desde GitHub Secrets
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Instalar browsers
        run: npx playwright install --with-deps

      # Opcional: sólo API Tests (mientras estabilizás E2E)
      # - run: npx playwright test --project="API Tests" --reporter=html

      # Completo: corre todo
      - run: npx playwright test --reporter=html

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
